### ISSUE TITLE
Incorrect build instructions url

### ISSUE THREAD

**Issue by jagill** [artclarke/xuggle-xuggler#1]
In the INSTALL document, it says:

```
See here for complete (and updated) install instructions:

  http://www.xuggle.com/xuggler/downloads/build.jsp
```

But going to that location returns a 404!

What's the actual location?

**Comment by artclarke** [comment]
http://www.xuggle.com/xuggler/build

On Wed, Mar 14, 2012 at 4:31 PM, James Gill <
reply@reply.github.com

> wrote:
> 
> In the INSTALL document, it says:
> 
>    See here for complete (and updated) install instructions:
> 
> ```
>  http://www.xuggle.com/xuggler/downloads/build.jsp
> ```
> 
> But going to that location returns a 404!
> 
> What's the actual location?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/xuggle/xuggle-xuggler/issues/1

## 

http://www.xuggle.com/
xu‧ggle (zŭ' gl) v. To freely encode, decode, and experience audio and
video.

Use Xuggle to get the power of FFmpeg in Java.
