### ISSUE TITLE
Update ffmpeg to the latest version

### ISSUE THREAD

**Issue by jkolobok** [artclarke/xuggle-xuggler#16]
The latest version of ffmpeg is 1.2. xuggler is currently linked to 0.10.2.  
For example 1.0 has fixed  an issue with jpeg stream over rtp.

**Comment by i30817** [comment]
Hope that when Atrac3+ is finally implemented in ffmpg, that the library is updated ;) (it's used by jpcsp which needs that codec for sound in most videos).

**Comment by artclarke** [comment]
I will not fix this in Xuggle -- the xuggle code-base requires significant rework to work with ffmpeg 2.x.

**Comment by jkolobok** [comment]
Even ffmpeg 1.2 would be good too.

**Comment by He-Pin** [comment]
thanks artclarke.i use xuggler once ~nice and cute project.

**Comment by artclarke** [comment]
i'm no longer working on the xuggle code-base period -- there are too many chances necessary to have it stay current. that includes 1.2. sorry.

**Comment by He-Pin** [comment]
@artclarke 
maybe you could update some document
then some one could continue your work,and you could play an team manager ,merge and review.

**Comment by artclarke** [comment]
Tried that; no one took up the role. Instead, I am working on an alternate
way to get to ffmpeg 2.0 using a different more updated code-base.
- Art

**Comment by He-Pin** [comment]
@artclarke yeah,just like netty,so many Chinese mobile game company use it,but no one commit one line code or even report some issue.

by the way,does the current code base contains all the code of xuggler?

I think how about you start an new project,and provide  skeleton,then all the codec could just as an plugin?if you update the document,I believe will so many people contribute to it,cause github is better than google code.

all in all,it all up to you,thanks,cause i used you code in this
https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-examples/webcam-capture-live-streaming
that's great!
