### ISSUE TITLE
Maven repository support for platform-specific artifacts

### ISSUE THREAD

**Issue by TinusTinus** [artclarke/xuggle-xuggler#17]
The main Xuggler artifact is available as a Maven dependency in the Xuggler Maven repository (see [issue 79](http://code.google.com/p/xuggle/issues/detail?id=79) at Google Code).

It would be great if the noarch jar and the platform-specific Xuggler jars were also available as Maven dependencies. The files are in http://xuggle.googlecode.com/svn/trunk/repo/share/java/, but the directory structure doesn't follow Maven conventions, so there is currently no way to include them as a dependency in a Maven project.

As an example, I would like to be able to add the noarch jar to my project like this:

```
<dependency>
    <groupId>xuggle</groupId>
    <artifactId>xuggle-xuggler-noarch</artifactId>
    <version>${xuggler.version}</version>
</dependency>
```

My current workaround is to download the jar manually and install it into my local repository:

```
mvn install:install-file -Dfile=xuggle-xuggler-noarch-5.4.jar -DgroupId=xuggle -DartifactId=xuggle-xuggler-noarch -Dversion=5.4 -Dpackaging=jar
```

(I already filed [this issue](http://code.google.com/p/xuggle/issues/detail?id=308) at Google Code, before I realised the project had moved to Github.)

**Comment by artclarke** [comment]
This will not be fixed in xuggler (at least by me). It's too difficult with the current build system.

That said... perhaps a successor project might do this better (which I may be working on).
