### ISSUE TITLE
OutOfMemory error

### ISSUE THREAD

**Issue by unnivm** [artclarke/xuggle-xuggler#24]
I searched for a while to resolve this issue when I am encoding a large video file(>100 mb) with an audio file.
As per some other threads, I followed your JNIMemoryManager. class to understand the memory related issues. 
This is what I have done in my code before the muxing when I faced the above error. 

JNIMemoryManager.setMemoryModel(MemoryModel.NATIVE_BUFFERS);

Still I am getting the error.

My OS is: Windows 7 32 bit

Any hint would be much appreciated.

Thanks,
Unni

**Comment by artclarke** [comment]
pretty impossible to guess at this without code to see what you're doing :(

**Comment by unnivm** [comment]
Hello Clarke,

I have solved that issue in a different way so that is the reason I did not
pursue that.  However, now I am facing a different issue. I am adding here
with the code:

I created MediaWriter Object:
writer = ToolFactory.makeWriter(outputFilename);

Then I got my screen size:
screenBounds = Toolkit.getDefaultToolkit().getScreenSize();

screenBounds.width = 1225;  // avi format will work with these resolution
screenBounds.height = 736;  // avi format will work with these resolution

 writer.open();
 writer.addVideoStream(0, 0,  screenBounds.width, screenBounds.height);

If I do like this , I am getting the following runtime exception: The above
code looks pretty straight forward.

Exception in thread "main" java.lang.RuntimeException: could not open
stream com.xuggle.xuggler.IStream@76547664
[index:0;id:0;streamcoder:com.xuggle.xuggler.IStreamCoder@76547720
[codec=com.xuggle.xuggler.ICodec@76481776[type=CODEC_TYPE_VIDEO;id=CODEC_ID_H264;name=libx264;];time
base=1/1000000;frame rate=0/0;pixel
type=YUV420P;width=1225;height=736;];framerate:0/0;timebase:1/90000;direction:OUTBOUND;]:
Operation not permitted

Because I am developing a screen recorder for my client.

 But if I comment the above line, then it will work

//screenBounds.width = 1225;  // avi format will work with these resolution
//  screenBounds.height = 736;  // avi format will work with these
resolution

It will work as expected !.

This looks quiet interesting, I am leaving the video type open so that the
frame work can decide which codec to be used based on the extension. The
above error will happen if we use .mp4/.mov

Any clue what I am doing wrong here.

Thanks for your framework,

Yours Sincerely,
Unni Mana

On Mon, Nov 23, 2015 at 4:29 AM, Art Clarke notifications@github.com
wrote:

> pretty impossible to guess at this without code to see what you're doing :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/artclarke/xuggle-xuggler/issues/24#issuecomment-158816652
> .

## 

---

If not played, Free Sudoku Android Game
https://play.google.com/store/apps/details?id=com.gamerfan.sudoku

**Comment by unnivm** [comment]
Hello!,

I was able to handle this issue. When I select recording area is odd
number, then it is throwing the above Runtime exception. However, I managed
it by changing to even number in my capturing area so that it is working,

You can close this issue,

Thanks,

Unni

On Mon, Nov 23, 2015 at 8:57 AM, unni mana unnivm@gmail.com wrote:

> Hello Clarke,
> 
> I have solved that issue in a different way so that is the reason I did
> not pursue that.  However, now I am facing a different issue. I am adding
> here with the code:
> 
> I created MediaWriter Object:
> writer = ToolFactory.makeWriter(outputFilename);
> 
> Then I got my screen size:
> screenBounds = Toolkit.getDefaultToolkit().getScreenSize();
> 
> screenBounds.width = 1225;  // avi format will work with these resolution
> screenBounds.height = 736;  // avi format will work with these resolution
> 
>  writer.open();
>  writer.addVideoStream(0, 0,  screenBounds.width, screenBounds.height);
> 
> If I do like this , I am getting the following runtime exception: The
> above code looks pretty straight forward.
> 
> Exception in thread "main" java.lang.RuntimeException: could not open
> stream com.xuggle.xuggler.IStream@76547664
> [index:0;id:0;streamcoder:com.xuggle.xuggler.IStreamCoder@76547720
> [codec=com.xuggle.xuggler.ICodec@76481776[type=CODEC_TYPE_VIDEO;id=CODEC_ID_H264;name=libx264;];time
> base=1/1000000;frame rate=0/0;pixel
> type=YUV420P;width=1225;height=736;];framerate:0/0;timebase:1/90000;direction:OUTBOUND;]:
> Operation not permitted
> 
> Because I am developing a screen recorder for my client.
> 
>  But if I comment the above line, then it will work
> 
> //screenBounds.width = 1225;  // avi format will work with these resolution
> //  screenBounds.height = 736;  // avi format will work with these
> resolution
> 
> It will work as expected !.
> 
> This looks quiet interesting, I am leaving the video type open so that the
> frame work can decide which codec to be used based on the extension. The
> above error will happen if we use .mp4/.mov
> 
> Any clue what I am doing wrong here.
> 
> Thanks for your framework,
> 
> Yours Sincerely,
> Unni Mana
> 
> On Mon, Nov 23, 2015 at 4:29 AM, Art Clarke notifications@github.com
> wrote:
> 
> > pretty impossible to guess at this without code to see what you're doing
> > :(
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/artclarke/xuggle-xuggler/issues/24#issuecomment-158816652
> > .
> 
> ## 
> 
> ---
> 
> If not played, Free Sudoku Android Game
> https://play.google.com/store/apps/details?id=com.gamerfan.sudoku

## 

---

If not played, Free Sudoku Android Game
https://play.google.com/store/apps/details?id=com.gamerfan.sudoku
