### ISSUE TITLE
Add a build target for generating a 'sources' and 'javadoc' JAR for the repository

### ISSUE THREAD

**Issue by naftulikay** [artclarke/xuggle-xuggler#3]
It'd be really nice to be able to have a 'sources' and 'javadoc' JAR in the repository to make it easier developing against Xuggle in Eclipse with m2eclipse. If you add a 'sources' and 'javadoc' JAR to the repository, m2eclipse will download these JARs to add documentation to code completion and to be able to look into what's going on inside of class files. In Maven, all that needs to be added is the following plugins:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-source-plugin</artifactId>
    <executions>
        <execution>
            <id>attach-source</id>
            <goals>
                <goal>jar</goal>
            </goals>
        </execution>
    </executions>
</plugin>
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-javadoc-plugin</artifactId>
    <executions>
        <execution>
            <id>attach-javadoc</id>
            <goals>
                <goal>jar</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by artclarke** [comment]
I answered this previously :). It seems like a simple feature but is not.  It requires help from ivy and xuggler build system changes.  And, if you read the code conventions section on my web site, build system changes have a two drink minimum.  Unfortunately, I do not drink.

Patches welcome though.

**Comment by naftulikay** [comment]
I don't mean to be a troll, but is the reason that you chose Ant and Ivy is because Maven is unable to do what you need for the project? They're using Ant over at Red5 and it drives me insane. I assume that Maven could do whatever you need to do, but am I mistaken?

**Comment by artclarke** [comment]
I choose ant originally because red5 and Robert used it at the time.  The Xuggle build system became complicated once c and assembly became required.  Now it's just not worth the effort to redo in maven IMO, although I do new projects with maven.

Now mr troll, patches welcome :)

**Comment by naftulikay** [comment]
![](http://images4.wikia.nocookie.net/__cb20111214064523/halo/images/d/dc/Troll_face.png)

**Comment by artclarke** [comment]
will not fix in xuggle
