### ISSUE TITLE
Filtering support (e.g. such as Yadif)

### ISSUE THREAD

**Issue by Lisyara** [artclarke/xuggle-xuggler#8]
It ll be marvelous if Xuggler will support filtering.  Is it possible to add this functionality?
I found some patches on https://groups.google.com/forum/?fromgroups=#!topic/xuggler-users/Dl1sMnCZvLw, but they fail on some files because of they were generated on elder version of Xuggle (and I can not guess it).  This feature will save me and others from lots of headache...
 Thanks a lot!

**Comment by artclarke** [comment]
will not fix in xuggle.
